// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBCsabpR5o0XpaJBL_Q7EgoQL3Io7IAI',
    appId: '1:959091538131:web:aed324723d2a3678aabc26',
    messagingSenderId: '959091538131',
    projectId: 'settrack-app-2026',
    authDomain: 'settrack-app-2026.firebaseapp.com',
    storageBucket: 'settrack-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDnZWvDV0P0JzPyAqxPzmwwqDlqa7jdAc',
    appId: '1:959091538131:android:9e9c712ae5e64a32aabc26',
    messagingSenderId: '959091538131',
    projectId: 'settrack-app-2026',
    storageBucket: 'settrack-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKqG1rlNBXBPoy-BepjPxILYTb-8kSBc',
    appId: '1:959091538131:ios:b1d46446576cb9ceaabc26',
    messagingSenderId: '959091538131',
    projectId: 'settrack-app-2026',
    storageBucket: 'settrack-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.settrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKqG1rlNBXBPoy-BepjPxILYTb-8kSBc',
    appId: '1:959091538131:ios:b1d46446576cb9ceaabc26',
    messagingSenderId: '959091538131',
    projectId: 'settrack-app-2026',
    storageBucket: 'settrack-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.settrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWBCsabpR5o0XpaJBL_Q7EgoQL3Io7IAI',
    appId: '1:959091538131:web:e7fecbbb6305576caabc26',
    messagingSenderId: '959091538131',
    projectId: 'settrack-app-2026',
    authDomain: 'settrack-app-2026.firebaseapp.com',
    storageBucket: 'settrack-app-2026.firebasestorage.app',
  );
}
